GigHub/Models/Gig.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GigHub.Models
{
  public class Gig
  {
    public int Id { get; set; }

    [Required]
    public ApplicationUser Artist { get; set; }

    public DateTime DateTime { get; set; }

    [Required]
    [StringLength(255)]
    public string Venue { get; set; }

    [Required]
    public Genre Gernre { get; set; }
  }

  public class Genre
  {
    public byte Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Name { get; set; }
  }
}

GigHub/Controllers/GigsController.cs
using GigHub.Models;
using GigHub.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace GigHub.Controllers
{
    public class GigsController : Controller
    {
        private ApplicationDbContext _context;
        public GigsController()
        {
            _context = new ApplicationDbContext();
        }

        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new GigFormViewModel
            {
                Genres = _context.Genres.ToList()
            };
            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(GigFormViewModel viewModel)
        {
          Gig gig = new Gig();
          string currentUserId = User.Identity.GetUserId();
          ApplicationUser currentUser = _context.Users.First();//.FirstOrDefault(x => x.Id == currentUserId);
          gig.Artist = currentUser;
          gig.Venue = viewModel.Venue;
          //gig.Id = 1;
          gig.DateTime = DateTime.Now;

          Genre genre = new Genre();
          //genre.Id = 2;
          genre.Name = "Jazz";

          gig.Gernre = genre;

          _context.Gigs.Add(gig);
          _context.SaveChanges();

          //gig.Artist = UserManager.FindById(User.Identity.GetUserId());
          //gig.Artist = viewModel.a
          //_context.Gigs.Add(new Gig() { Gernre = viewModel.Genre});
          return RedirectToAction("Index", "Home");
        }
    }
}

GigHub/Views/Gigs/Create.cshtml
@model GigHub.ViewModels.GigFormViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Add a Gig</h2>
@using (Html.BeginForm("Create", "Gigs"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Venue)
        @Html.TextBoxFor(m => m.Venue, new { @class = "form-control" })
        @*<label for="Venue">Venue</label>
            <input type="email" class="form-control" id="Venue" placeholder="Venue">*@
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Time)
        @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Genre)
        @Html.DropDownListFor(m => m.Genre, new SelectList(Model.Genres, "Id", "Name"), Model.Genres.FirstOrDefault().Name, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
}